### ISSUE TITLE
Отредактировать пример для соответствия стандартам с++

### ISSUE THREAD

**Issue by Ted-Denisenko** [Ted-Denisenko/HashTable#2]
В примере есть много СИ-шных функций (например strcpy) и устаревших конструкций (например, typedef)
Их следует заменить на аналоги функций в С++ и использовать более новые конструкции

**Comment by dr-silence** [comment]
@Ted-Denisenko На данный момент нет особого смысла. Полезней направить усилия на усвоение устройства хеш-таблицы.

Подобный рефакторинг не делается ради самого рефакторинга, то есть не делается лишь ради собственно замены всех вызовы той же strcpy вызовами её C++ аналога. А делается ради того, чтобы добиться каких-то положительных результатов. Например, избавиться от потенциальных уязвимостей, порождаемых использованием той же strcpy. Избавление же от уязвимостей, порождаемых strcpy, требует изучения совсем других тем, и отвлекает от изучения хеш-таблицы.

**Comment by dr-silence** [comment]
Например, в общем случае нельзя просто взять и заменить вызовы malloc/calloc вызовами оператора new. Ибо в случае нехватки памяти оператор new, в отличие от malloc/calloc, не возвращает nullptr, а порождает исключение. Пример последствий такой простой замены: 
[new_instead_of_malloc.zip](https://github.com/Ted-Denisenko/HashTable/files/9275575/new_instead_of_malloc.zip)
.

**Comment by dr-silence** [comment]
Если же рассматривать malloc/calloc и new, то отличия в использовании этих способов выделения памяти представлены в 
[new_vs_alloc.zip](https://github.com/Ted-Denisenko/HashTable/files/9275581/new_vs_alloc.zip).

**Comment by Ted-Denisenko** [comment]
Понял. На данный момент есть более важные задачи, эту закрываю
